### PR TITLE
Add files

### PR DESCRIPTION
**Pull request by Alimasa-Eliza**
Please review my files. Thank you!

### CODE REVIEW

**Review by tapispisan-yves — CHANGES_REQUESTED** [review]
For index.html; 
On line 34 of your index.html, I think you can add a few indentations since its inside a different div element than the rest from the outside hr element. For readability purposes.

Line 92, all class names should be on kebab cases, all lower case separated by hyphen each word. See this reference for clarification. 
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_5

Lines 80-121, check every line for correct indentation. Like on lines 83 and 84, the div and ul element is in the same indent lines, and it is not a good practice. You can check this link for more explanation. 
https://www.freecodecamp.org/news/how-to-indent-in-html-and-why-it-is-important/

And for your test htmls, please observe proper indentations.

**Comment by Alimasa-Eliza** [comment]
Hello, I've resolved the issue. Please review my files again, thank you!

**Review by tapispisan-yves — CHANGES_REQUESTED** [review]
I don't think my intent is properly received and I'm sorry if there is any confusing part in my review. Here is what it looks like with proper indentation on your html files. And check for changes in your index.html files with your css files or your css file wont work. 

I also didn't see any changes in your index.html, please refer to the first comment for that. 
You can use prettier, an extension in your visual studio code, for it to look like this, but don't put all your trust in prettier, double check it if needed. If there is anymore confusing part, you can reply to this comment.
sample

**Comment by Alimasa-Eliza** [comment]
Thanks for your feedback! I've resolved the issue and used prettier as suggested. Please review my files again.

**Review by tapispisan-yves — APPROVED** [review]
On your index.html lines 111, 120, 154, 163, 172, 181, and 190, you can move the closing tag up so that it is connected to the last part of their respective end lines and there is no unnecessary lines.

I think you forgot to use prettier on your test htmls. You can do that there too and you can proceed with your exercise.

**Comment by Alimasa-Eliza** [comment]
Hello again, I've resolved the issue. Could you please review my file once more?

**Review by tapispisan-yves — APPROVED** [review]
Good job! You can merge it now.

**Comment by Alimasa-Eliza** [comment]
Thank you!

**Pull request merged**
